### ISSUE TITLE
[Week2] First draft of specification

### ISSUE THREAD

**Issue by tyly324** [tyly324/ARC#1]
- Speed:150MHz
- Throughout: 5 stages pipeline
- Energy: 2.5W
- Completeness of instruction:  [Simplified MIPS32® Instruction Set](http://www.imgtec.com/downloads/factsheets/MD00565-2B-MIPS32-QRC-01.01.pdf)

etc...
那个etc还有啥捏~~~
整个cache，mmu啥的~~
还有
1. instruction memory和data memory
2. 32个32bit registers
3. 。。继续补充

// i'm so freaking hungry
//go to bed, have a dream of dinner

**Comment by shanyueGG** [comment]
Speed:150MHz
Throughout: 5 stages pipeline
Energy: 2.5W
Completeness of instruction:
etc...
